name = "wireguard-dns-generator"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

[[kv_namespaces]]
binding = "DB"
id = "c05fa9ee874a402791a621bb4df3db4e"
preview_id = "YOUR_KV_PREVIEW_NAMESPACE_ID"

[vars]
WEBSITE_URL = "https://free-config.pages.dev/"
ADMIN_ID = "7240662021"
BOT_TOKEN = "8460423026:AAEWBzpT3UmyXtDG-XW6xbvoORnk5ssawqM"
